// frontend/src/app/components/status-message.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core'

export type MessageTone = 'neutral' | 'success' | 'error'
export type StatusMessageValue = { text: string; tone: MessageTone } | null

/**
 * Single persistent aria-live region for form/mutation feedback.
 *
 * Kept rendered at all times (even with empty text) so assistive tech keeps
 * announcing updates reliably, while color/weight give sighted users a way
 * to tell an error apart from a success message at a glance instead of
 * having to read the copy.
 */
@Component({
  selector: 'app-status-message',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<p aria-live="polite" class="text-sm" [class]="toneClass()">{{ value()?.text ?? '' }}</p>`,
})
export class StatusMessageComponent {
  readonly value = input<StatusMessageValue>(null)

  protected toneClass() {
    switch (this.value()?.tone) {
      case 'error':
        return 'text-error font-medium'
      case 'success':
        return 'text-success'
      default:
        return 'text-text-secondary'
    }
  }
}

// frontend/src/components/StatusMessage.tsx
import { Text } from '@radix-ui/themes'

export type MessageTone = 'neutral' | 'success' | 'error'
export type StatusMessageValue = { text: string; tone: MessageTone } | null

/**
 * Single persistent aria-live region for form/mutation feedback.
 *
 * Kept mounted at all times (even with empty text) so assistive tech keeps
 * announcing updates reliably, while color/weight give sighted users a way
 * to tell an error apart from a success message at a glance instead of
 * having to read the copy.
 */
export function StatusMessage({ value }: { value: StatusMessageValue }) {
  const tone = value?.tone ?? 'neutral'
  return (
    <Text
      aria-live="polite"
      as="p"
      color={tone === 'error' ? 'red' : tone === 'success' ? 'grass' : 'gray'}
      weight={tone === 'error' ? 'medium' : undefined}
      size="2"
    >
      {value?.text ?? ''}
    </Text>
  )
}
