// frontend/src/app/pages/dashboard-page.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core'
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms'
import { MatButton } from '@angular/material/button'
import { MatCard, MatCardContent } from '@angular/material/card'
import { MatError, MatFormField, MatLabel } from '@angular/material/form-field'
import { MatInput } from '@angular/material/input'
import { MatOption, MatSelect } from '@angular/material/select'
import { RouterLink } from '@angular/router'
import { QueryClient, injectMutation, injectQuery } from '@tanstack/angular-query-experimental'
import { AlertComponent } from '../components/alert.component'
import { ForbiddenComponent } from '../components/forbidden.component'
import { QueryErrorComponent } from '../components/query-error.component'
import { StatusMessageComponent, type StatusMessageValue } from '../components/status-message.component'
import { isForbidden, request } from '../lib/api'
import { injectDocumentTitle } from '../lib/document-title'
import { errorMessage, submitForm } from '../lib/form-validation'
import { queryKeys } from '../lib/query-keys'

type Workspace = {
  id: string
  name: string
  myRole: string
}

type Project = {
  id: string
  workspaceId: string
  name: string
  description?: string
}

type NameValues = { name: string }

const NAME_MESSAGES = { required: 'Name is required' }

function nameForm() {
  return new FormGroup({ name: new FormControl('', { nonNullable: true, validators: Validators.required }) })
}

async function fetchWorkspaces() {
  await request('/api/auth/csrf')
  return request<Workspace[]>('/api/workspaces')
}

function errorText(error: unknown, fallback: string) {
  return error instanceof Error ? error.message : fallback
}

@Component({
  selector: 'app-dashboard-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    AlertComponent,
    ForbiddenComponent,
    MatButton,
    MatCard,
    MatCardContent,
    MatError,
    MatFormField,
    MatInput,
    MatLabel,
    MatOption,
    MatSelect,
    QueryErrorComponent,
    ReactiveFormsModule,
    RouterLink,
    StatusMessageComponent,
  ],
  template: `
    @if (workspacesQuery.isLoading()) {
      <main><p aria-live="polite">Loading dashboard...</p></main>
    } @else if (forbidden()) {
      <app-forbidden message="You don't have access to this dashboard." />
    } @else if (workspacesFailed()) {
      <main>
        <app-query-error message="We couldn't load your workspaces." (retry)="workspacesQuery.refetch()" />
      </main>
    } @else {
      <main class="flex flex-col gap-8">
        <div class="flex flex-col gap-3">
          <p class="eyebrow">TeamFlow workspace</p>
          <h1 class="page-title">Project dashboard</h1>
          <p class="muted">Create a workspace, then give it a project to hold future tasks.</p>
        </div>

        <mat-card appearance="outlined" class="app-card">
          <mat-card-content>
            <form
              class="flex flex-col gap-3 sm:flex-row sm:items-start"
              [formGroup]="workspaceForm"
              (ngSubmit)="createWorkspace()"
              novalidate
            >
              <mat-form-field class="w-full">
                <mat-label>New workspace</mat-label>
                <input matInput formControlName="name" maxlength="120" />
                <mat-error role="alert">{{ nameError(workspaceForm) }}</mat-error>
              </mat-form-field>
              <button
                matButton="filled"
                type="submit"
                class="shrink-0 whitespace-nowrap sm:mt-1"
                [disabled]="createWorkspaceMutation.isPending()"
              >
                Create workspace
              </button>
            </form>
          </mat-card-content>
        </mat-card>

        @if (workspaces().length === 0) {
          <app-alert severity="info" role="status">No workspaces yet.</app-alert>
        } @else {
          <mat-form-field class="max-w-[20rem]">
            <mat-label>Workspace</mat-label>
            <mat-select [value]="activeWorkspace()" (selectionChange)="selectedWorkspace.set($event.value)">
              @for (workspace of workspaces(); track workspace.id) {
                <mat-option [value]="workspace.id">{{ workspace.name }} ({{ workspace.myRole }})</mat-option>
              }
            </mat-select>
          </mat-form-field>

          <mat-card appearance="outlined" class="app-card">
            <mat-card-content>
              <form
                class="flex flex-col gap-3 sm:flex-row sm:items-start"
                [formGroup]="projectForm"
                (ngSubmit)="createProject()"
                novalidate
              >
                <mat-form-field class="w-full">
                  <mat-label>New project</mat-label>
                  <input matInput formControlName="name" maxlength="120" />
                  <mat-error role="alert">{{ nameError(projectForm) }}</mat-error>
                </mat-form-field>
                <button
                  matButton="filled"
                  type="submit"
                  class="shrink-0 whitespace-nowrap sm:mt-1"
                  [disabled]="createProjectMutation.isPending()"
                >
                  Create project
                </button>
              </form>
            </mat-card-content>
          </mat-card>

          <section class="flex flex-col gap-3" aria-labelledby="projects-heading">
            <h2 class="section-title" id="projects-heading">Projects</h2>
            @if (projectsFailed()) {
              <app-query-error
                message="We couldn't load projects for this workspace."
                (retry)="projectsQuery.refetch()"
              />
            } @else if (projects().length === 0) {
              <app-alert severity="info" role="status">No projects in this workspace yet.</app-alert>
            } @else {
              <div class="flex flex-col gap-3">
                @for (project of projects(); track project.id) {
                  <mat-card appearance="outlined" class="app-card">
                    <mat-card-content class="flex flex-wrap items-center justify-between gap-3">
                      <div>
                        <p class="font-bold">{{ project.name }}</p>
                        <p class="muted text-sm">{{ project.description ?? 'Ready for tasks' }}</p>
                      </div>
                      <a [routerLink]="['/projects', project.id, 'tasks']" [attr.aria-label]="'Open task board for ' + project.name">
                        Open task board
                      </a>
                    </mat-card-content>
                  </mat-card>
                }
              </div>
            }
          </section>

          <p><a [routerLink]="['/workspaces', activeWorkspace(), 'members']">Manage members</a></p>
        }

        @if (actionForbidden()) {
          <app-alert severity="error">
            You don't have permission to do that. This action requires a higher role in this workspace.
          </app-alert>
        }
        <app-status-message [value]="message()" />
      </main>
    }
  `,
})
export class DashboardPageComponent {
  private readonly queryClient = inject(QueryClient)

  protected readonly selectedWorkspace = signal('')
  protected readonly message = signal<StatusMessageValue>(null)
  protected readonly actionForbidden = signal(false)

  protected readonly workspacesQuery = injectQuery(() => ({
    queryKey: queryKeys.workspaces.all(),
    queryFn: fetchWorkspaces,
  }))
  protected readonly workspaces = computed(() => this.workspacesQuery.data() ?? [])

  // Falls back to the first workspace until the user explicitly picks one, so a
  // freshly created (or freshly loaded) workspace is usable without an extra click.
  protected readonly activeWorkspace = computed(() => this.selectedWorkspace() || this.workspaces()[0]?.id || '')

  protected readonly projectsQuery = injectQuery(() => ({
    queryKey: queryKeys.workspaces.projects(this.activeWorkspace()),
    queryFn: () => request<Project[]>(`/api/workspaces/${this.activeWorkspace()}/projects`),
    enabled: !!this.activeWorkspace(),
  }))
  protected readonly projects = computed(() => this.projectsQuery.data() ?? [])

  protected readonly forbidden = computed(
    () => isForbidden(this.workspacesQuery.error()) || isForbidden(this.projectsQuery.error()),
  )
  protected readonly workspacesFailed = computed(
    () => this.workspacesQuery.isError() && !isForbidden(this.workspacesQuery.error()),
  )
  protected readonly projectsFailed = computed(
    () => this.projectsQuery.isError() && !isForbidden(this.projectsQuery.error()),
  )

  protected readonly workspaceForm = nameForm()
  protected readonly projectForm = nameForm()

  protected readonly createWorkspaceMutation = injectMutation(() => ({
    mutationFn: (values: NameValues) =>
      request<Workspace>('/api/workspaces', { method: 'POST', body: JSON.stringify(values) }),
    onSuccess: (workspace: Workspace) => {
      this.workspaceForm.reset()
      void this.queryClient.invalidateQueries({ queryKey: queryKeys.workspaces.all() })
      this.selectedWorkspace.set(workspace.id)
      this.message.set({ text: 'Workspace created', tone: 'success' })
    },
    onError: (error: unknown) => {
      if (isForbidden(error)) this.actionForbidden.set(true)
      this.message.set({ text: errorText(error, 'Unable to create workspace'), tone: 'error' })
    },
  }))

  protected readonly createProjectMutation = injectMutation(() => ({
    mutationFn: (values: NameValues) =>
      request(`/api/workspaces/${this.activeWorkspace()}/projects`, { method: 'POST', body: JSON.stringify(values) }),
    onSuccess: () => {
      this.projectForm.reset()
      void this.queryClient.invalidateQueries({ queryKey: queryKeys.workspaces.projects(this.activeWorkspace()) })
      this.message.set({ text: 'Project created', tone: 'success' })
    },
    onError: (error: unknown) => {
      if (isForbidden(error)) this.actionForbidden.set(true)
      this.message.set({ text: errorText(error, 'Unable to create project'), tone: 'error' })
    },
  }))

  constructor() {
    injectDocumentTitle(() => 'Dashboard')
  }

  protected nameError(form: ReturnType<typeof nameForm>) {
    return errorMessage(form.controls.name, NAME_MESSAGES)
  }

  protected createWorkspace() {
    const values = submitForm(this.workspaceForm)
    if (!values) return
    this.actionForbidden.set(false)
    this.createWorkspaceMutation.mutate(values)
  }

  protected createProject() {
    const values = submitForm(this.projectForm)
    if (!values) return
    this.actionForbidden.set(false)
    this.createProjectMutation.mutate(values)
  }
}

// frontend/src/pages/DashboardPage.tsx
import { useState } from 'react'
import { useForm } from '@tanstack/react-form'
import { z } from 'zod'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link as RouterLink } from 'react-router-dom'
import Alert from '@mui/material/Alert'
import Box from '@mui/material/Box'
import Button from '@mui/material/Button'
import Card from '@mui/material/Card'
import CardContent from '@mui/material/CardContent'
import Link from '@mui/material/Link'
import MenuItem from '@mui/material/MenuItem'
import Stack from '@mui/material/Stack'
import TextField from '@mui/material/TextField'
import Typography from '@mui/material/Typography'
import { isForbidden, request } from '../lib/api.ts'
import { firstErrorMessage } from '../lib/formError.ts'
import { queryKeys } from '../lib/queryKeys.ts'
import { Forbidden } from '../components/Forbidden.tsx'
import { QueryError } from '../components/QueryError.tsx'
import { StatusMessage, type StatusMessageValue } from '../components/StatusMessage.tsx'
import { useDocumentTitle } from '../lib/useDocumentTitle.ts'

type Workspace = {
  id: string
  name: string
  myRole: string
}

type Project = {
  id: string
  workspaceId: string
  name: string
  description?: string
}

const workspaceSchema = z.object({
  name: z.string().min(1, 'Name is required').max(120),
})

const projectSchema = z.object({
  name: z.string().min(1, 'Name is required').max(120),
})

type WorkspaceValues = z.infer<typeof workspaceSchema>
type ProjectValues = z.infer<typeof projectSchema>

async function fetchWorkspaces() {
  await request('/api/auth/csrf')
  return (await request('/api/workspaces')) as Workspace[]
}

export function DashboardPage() {
  useDocumentTitle('Dashboard')
  const [selectedWorkspace, setSelectedWorkspace] = useState('')
  const [message, setMessage] = useState<StatusMessageValue>(null)
  const [actionForbidden, setActionForbidden] = useState(false)
  const queryClient = useQueryClient()

  const workspacesQuery = useQuery({ queryKey: queryKeys.workspaces.all(), queryFn: fetchWorkspaces })
  const workspaces = workspacesQuery.data ?? []
  // Falls back to the first workspace until the user explicitly picks one, so a
  // freshly created (or freshly loaded) workspace is usable without an extra click.
  const activeWorkspace = selectedWorkspace || workspaces[0]?.id || ''

  const projectsQuery = useQuery({
    queryKey: queryKeys.workspaces.projects(activeWorkspace),
    queryFn: () => request(`/api/workspaces/${activeWorkspace}/projects`) as Promise<Project[]>,
    enabled: !!activeWorkspace,
  })
  const projects = projectsQuery.data ?? []

  const workspaceForm = useForm({
    defaultValues: { name: '' } as WorkspaceValues,
    validators: { onSubmit: workspaceSchema },
    onSubmit: ({ value }) => {
      setActionForbidden(false)
      createWorkspaceMutation.mutate(value)
    },
  })
  const projectForm = useForm({
    defaultValues: { name: '' } as ProjectValues,
    validators: { onSubmit: projectSchema },
    onSubmit: ({ value }) => {
      setActionForbidden(false)
      createProjectMutation.mutate(value)
    },
  })

  const createWorkspaceMutation = useMutation({
    mutationFn: (values: WorkspaceValues) =>
      request('/api/workspaces', { method: 'POST', body: JSON.stringify(values) }) as Promise<Workspace>,
    onSuccess: (workspace) => {
      workspaceForm.reset()
      void queryClient.invalidateQueries({ queryKey: queryKeys.workspaces.all() })
      setSelectedWorkspace(workspace.id)
      setMessage({ text: 'Workspace created', tone: 'success' })
    },
    onError: (error: unknown) => {
      if (isForbidden(error)) setActionForbidden(true)
      setMessage({ text: error instanceof Error ? error.message : 'Unable to create workspace', tone: 'error' })
    },
  })

  const createProjectMutation = useMutation({
    mutationFn: (values: ProjectValues) =>
      request(`/api/workspaces/${activeWorkspace}/projects`, { method: 'POST', body: JSON.stringify(values) }),
    onSuccess: () => {
      projectForm.reset()
      void queryClient.invalidateQueries({ queryKey: queryKeys.workspaces.projects(activeWorkspace) })
      setMessage({ text: 'Project created', tone: 'success' })
    },
    onError: (error: unknown) => {
      if (isForbidden(error)) setActionForbidden(true)
      setMessage({ text: error instanceof Error ? error.message : 'Unable to create project', tone: 'error' })
    },
  })

  const loading = workspacesQuery.isLoading
  const forbidden = isForbidden(workspacesQuery.error) || isForbidden(projectsQuery.error)
  const workspacesFailed = workspacesQuery.isError && !isForbidden(workspacesQuery.error)
  const projectsFailed = projectsQuery.isError && !isForbidden(projectsQuery.error)

  if (loading)
    return (
      <Box component="main">
        <Typography aria-live="polite">Loading dashboard...</Typography>
      </Box>
    )
  if (forbidden) return <Forbidden message="You don't have access to this dashboard." />
  if (workspacesFailed)
    return (
      <Box component="main">
        <QueryError message="We couldn't load your workspaces." onRetry={() => void workspacesQuery.refetch()} />
      </Box>
    )

  return (
    <Box component="main">
      <Stack spacing={4}>
        <Stack spacing={1.5}>
          <Typography variant="overline" color="primary.main" sx={{ fontWeight: 700, letterSpacing: '0.08em' }}>
            TeamFlow workspace
          </Typography>
          <Typography variant="h3" component="h1" sx={{ fontWeight: 700 }}>
            Project dashboard
          </Typography>
          <Typography component="p" color="text.secondary">
            Create a workspace, then give it a project to hold future tasks.
          </Typography>
        </Stack>

        <Card>
          <CardContent>
            <form
              onSubmit={(event) => {
                event.preventDefault()
                void workspaceForm.handleSubmit()
              }}
              noValidate
            >
              <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5} sx={{ alignItems: { xs: 'stretch', sm: 'flex-start' } }}>
                <workspaceForm.Field name="name">
                  {(field) => (
                    <TextField
                      label="New workspace"
                      fullWidth
                      value={field.state.value}
                      onChange={(event) => field.handleChange(event.target.value)}
                      onBlur={field.handleBlur}
                      error={field.state.meta.errors.length > 0}
                      helperText={firstErrorMessage(field.state.meta.errors)}
                      slotProps={{ htmlInput: { maxLength: 120 }, formHelperText: { role: 'alert' } }}
                    />
                  )}
                </workspaceForm.Field>
                <Button type="submit" variant="contained" disabled={createWorkspaceMutation.isPending} className="shrink-0 whitespace-nowrap">
                  Create workspace
                </Button>
              </Stack>
            </form>
          </CardContent>
        </Card>

        {workspaces.length === 0 ? (
          <Alert severity="info" role="status">No workspaces yet.</Alert>
        ) : (
          <>
            <TextField
              select
              label="Workspace"
              value={activeWorkspace}
              onChange={(event) => setSelectedWorkspace(event.target.value)}
              sx={{ maxWidth: '20rem' }}
            >
              {workspaces.map((workspace) => (
                <MenuItem key={workspace.id} value={workspace.id}>
                  {workspace.name} ({workspace.myRole})
                </MenuItem>
              ))}
            </TextField>

            <Card>
              <CardContent>
                <form
                  onSubmit={(event) => {
                    event.preventDefault()
                    void projectForm.handleSubmit()
                  }}
                  noValidate
                >
                  <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.5} sx={{ alignItems: { xs: 'stretch', sm: 'flex-start' } }}>
                    <projectForm.Field name="name">
                      {(field) => (
                        <TextField
                          label="New project"
                          fullWidth
                          value={field.state.value}
                          onChange={(event) => field.handleChange(event.target.value)}
                          onBlur={field.handleBlur}
                          error={field.state.meta.errors.length > 0}
                          helperText={firstErrorMessage(field.state.meta.errors)}
                          slotProps={{ htmlInput: { maxLength: 120 }, formHelperText: { role: 'alert' } }}
                        />
                      )}
                    </projectForm.Field>
                    <Button type="submit" variant="contained" disabled={createProjectMutation.isPending} className="shrink-0 whitespace-nowrap">
                      Create project
                    </Button>
                  </Stack>
                </form>
              </CardContent>
            </Card>

            <Stack component="section" aria-labelledby="projects-heading" spacing={1.5}>
              <Typography variant="h5" component="h2" id="projects-heading" sx={{ fontWeight: 700 }}>
                Projects
              </Typography>
              {projectsFailed ? (
                <QueryError message="We couldn't load projects for this workspace." onRetry={() => void projectsQuery.refetch()} />
              ) : projects.length === 0 ? (
                <Alert severity="info" role="status">No projects in this workspace yet.</Alert>
              ) : (
                <Stack spacing={1.5}>
                  {projects.map((project) => (
                    <Card key={project.id}>
                      <CardContent>
                        <Stack direction="row" spacing={1.5} sx={{ justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap' }}>
                          <Stack>
                            <Typography sx={{ fontWeight: 700 }}>{project.name}</Typography>
                            <Typography variant="body2" color="text.secondary">
                              {project.description ?? 'Ready for tasks'}
                            </Typography>
                          </Stack>
                          <Link
                            component={RouterLink}
                            to={`/projects/${project.id}/tasks`}
                            aria-label={`Open task board for ${project.name}`}
                          >
                            Open task board
                          </Link>
                        </Stack>
                      </CardContent>
                    </Card>
                  ))}
                </Stack>
              )}
            </Stack>

            <Typography component="p">
              <Link component={RouterLink} to={`/workspaces/${activeWorkspace}/members`}>
                Manage members
              </Link>
            </Typography>
          </>
        )}

        {actionForbidden && (
          <Alert severity="error">
            You don't have permission to do that. This action requires a higher role in this workspace.
          </Alert>
        )}
        <StatusMessage value={message} />
      </Stack>
    </Box>
  )
}
