// frontend/src/app/pages/status-page.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core'
import { RouterLink } from '@angular/router'
import { HealthStatusComponent } from '../components/health-status.component'
import { injectDocumentTitle } from '../lib/document-title'

@Component({
  selector: 'app-status-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [HealthStatusComponent, RouterLink],
  template: `
    <main class="flex max-w-[34rem] flex-col gap-4">
      <h1 class="page-title">TeamFlow</h1>
      <p class="muted">Local skeleton is up when the API health check below reports <strong>UP</strong>.</p>
      <app-health-status />
      <p><a routerLink="/">Open account flow</a></p>
    </main>
  `,
})
export class StatusPageComponent {
  constructor() {
    injectDocumentTitle(() => 'Status')
  }
}

// frontend/src/pages/StatusPage.tsx
import { Link as RouterLink } from 'react-router-dom'
import { Box, Flex, Heading, Link, Text } from '@radix-ui/themes'
import { HealthStatus } from '../components/HealthStatus.tsx'
import { useDocumentTitle } from '../lib/useDocumentTitle.ts'

export function StatusPage() {
  useDocumentTitle('Status')
  return (
    <Box asChild maxWidth="34rem">
      <main>
        <Flex direction="column" gap="4">
          <Heading as="h1" size="8">
            TeamFlow
          </Heading>
          <Text as="p" color="gray" size="3">
            Local skeleton is up when the API health check below reports <Text weight="bold">UP</Text>.
          </Text>
          <HealthStatus />
          <Text as="p">
            <Link asChild>
              <RouterLink to="/">Open account flow</RouterLink>
            </Link>
          </Text>
        </Flex>
      </main>
    </Box>
  )
}
